spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sheepyu?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 20030519
  redis:
    host: localhost
    port: 6379
    database: 0
    password: 20030519
  mail:
    host: smtp.163.com
    username: ygq__future@163.com
    password: IKRFOJCYBTWFJFYC
    test-connection: true
    port: 465
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
# 详情请参照SwaggerProperties
sheepyu:
  sms:
    mail-enable: false
  swagger:
    product: true
  file:
    config:
      LOCAL:
        endpoint: http://localhost:18080
        path: /home/upload
logging:
  level:
    top.sheepyu: debug
