spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sheepyu?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 20030519
  redis:
    host: localhost
    port: 6379
    database: 0
    password: 20030519
  #一般云服务器都禁用了25端口, 所以正式部署需要使用邮件服务的请使用https的465端口
  mail:
    host: smtp.163.com
    username: ygq__future@163.com
    password: IKRFOJCYBTWFJFYC
    port: 465
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
# 详情请参照SwaggerProperties
sheepyu:
  web:
    demo: false
    demo-exclude-url:
      - /admin-api/system/user/login
      - /admin-api/system/user/refreshToken/*
  swagger:
    product: true
  file:
    config:
      LOCAL:
        endpoint: https://demo.sheepyu.top/api
        path: /home/upload
logging:
  level:
    top.sheepyu: debug
